### ISSUE TITLE
Improvement: Sign up error shows json object

### ISSUE THREAD

**Issue by NorDar** [sopra-fs24-group-01/sopra-fs24-plantparent-client#88]
When signing up a duplicate email the returned error message is a json object.:
![image](https://github.com/sopra-fs24-group-01/sopra-fs24-plantparent-client/assets/44843808/5d78b010-763b-483e-9d80-ca3a59794771)

Is this intended or not?

**Comment by Danielgergely** [comment]
Fixed the frontend, but also created a backend issue which states that the error message should be more specified. [#190](https://github.com/sopra-fs24-group-01/sopra-fs24-plantparent-server/issues/190)
