### ISSUE TITLE
Improvement: When adding a plant inside of a space it gets added to the user but not the space

### ISSUE THREAD

**Issue by NorDar** [sopra-fs24-group-01/sopra-fs24-plantparent-client#94]
The add plant button within a space creates a new plant. This plant is not automatically added to the space where the request was made from.
Is it possible to add this functionality?

**Comment by Danielgergely** [comment]
I can't reproduce this. Why I add plants to space, they are added. What exactly does not work?

**Comment by Danielgergely** [comment]
> The add plant button within a space creates a new plant. This plant is not automatically added to the space where the request was made from. Is it possible to add this functionality?

If a backend endpoint is created, then we can do this. Currently if we create a plant, it is not added to any space. Maybe an optional flag (spaceId) could be submitted to the createPlant endpoint which if specified would add this plant to the space. If this is implemented in the backend, I can add this flag in the frontend.

**Comment by M-Sigg** [comment]
I already started, will finish it later today

**Comment by Danielgergely** [comment]
This now also works in the frontend.
